/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tablet;

/**
 *
 * @author aluno
 */
public class Bebidas extends javax.swing.JFrame {

    /**
     * Creates new form Pratos
     */
    public Bebidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bebida4 = new javax.swing.JLabel();
        bebida3 = new javax.swing.JLabel();
        bebida1 = new javax.swing.JLabel();
        bebida2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ESCOLHA SUA BEBIDA");
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(null);

        bebida4.setBackground(new java.awt.Color(255, 0, 0));
        bebida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/MILKSHAKE.jpg"))); // NOI18N
        bebida4.setToolTipText("MILKSHAKE SABORES");
        bebida4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        bebida4.setOpaque(true);
        getContentPane().add(bebida4);
        bebida4.setBounds(540, 390, 325, 257);

        bebida3.setBackground(new java.awt.Color(0, 204, 255));
        bebida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/SUCO.jpg"))); // NOI18N
        bebida3.setToolTipText("<html>SUCOS DIVERSOS: Sucos naturais feitos com frutas frescas e selecionadas para garantir a qualidade<br>e o sabor.</html>");
        bebida3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        bebida3.setOpaque(true);
        getContentPane().add(bebida3);
        bebida3.setBounds(150, 390, 325, 257);

        bebida1.setBackground(new java.awt.Color(0, 204, 255));
        bebida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cervejadacasa.jpg"))); // NOI18N
        bebida1.setToolTipText("<html>CERVEJAS ARTESANAIS: A maior seleção de cervejas nacionais e importadas para você.<br>\nCervejas de diversos sabores e também as clássicas para sua Happy Hour.</html> ");
        bebida1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        bebida1.setOpaque(true);
        getContentPane().add(bebida1);
        bebida1.setBounds(150, 110, 325, 257);

        bebida2.setBackground(new java.awt.Color(255, 0, 0));
        bebida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Refrigerante.jpg"))); // NOI18N
        bebida2.setToolTipText("REFRIGERANTES LATA: Todos os sabores disponíveis.");
        bebida2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        bebida2.setOpaque(true);
        getContentPane().add(bebida2);
        bebida2.setBounds(540, 110, 325, 257);

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESCOLHA SUA BEBIDA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 40, 330, 40);

        jButton1.setBackground(new java.awt.Color(255, 102, 51));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 220, 60, 270);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bebidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bebida1;
    private javax.swing.JLabel bebida2;
    private javax.swing.JLabel bebida3;
    private javax.swing.JLabel bebida4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
