/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tablet;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import conexao.*;
import javax.swing.SwingUtilities;

/**
 *
 * @author aluno
 */
public class Cardapio extends javax.swing.JFrame {

    /**
     * Creates new form Cardapio
     */
    public Cardapio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Resumo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setName("Tela Principal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(null);

        Resumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/acompanhar.jpg"))); // NOI18N
        Resumo.setText("jLabel4");
        Resumo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Resumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResumoMouseClicked(evt);
            }
        });
        getContentPane().add(Resumo);
        Resumo.setBounds(670, 460, 210, 144);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/tabulerio.jpg"))); // NOI18N
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 440, 470, 170);

        jLabel7.setBackground(new java.awt.Color(51, 102, 255));
        jLabel7.setFont(new java.awt.Font("Bernard MT Condensed", 0, 46)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Sobremesas (1).jpg"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(660, 110, 220, 320);

        jLabel9.setBackground(new java.awt.Color(255, 51, 51));
        jLabel9.setFont(new java.awt.Font("Bernard MT Condensed", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cerveja-papel-de-parede-800x600-2638_17.jpg"))); // NOI18N
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(410, 110, 220, 320);

        jLabel8.setBackground(new java.awt.Color(51, 153, 0));
        jLabel8.setFont(new java.awt.Font("Bernard MT Condensed", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/HAMBURGUER.jpg"))); // NOI18N
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 110, 220, 320);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bernard MT Condensed", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ESCOLHA UMA OPÇÃO.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 50, 290, 60);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new Pratos().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new Bebidas().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new Sobremesas().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new Jogos().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked
    
    //BOTAO RESUMO
    private void ResumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResumoMouseClicked
        // TODO add your handling code here:
        Conexao CON = new Conexao();
        CON.Conectar();
        try{
            //Buscando nome dos integrantes e valores
            double valorIndividual;
            ArrayList<Double> valoresIndividuais = new ArrayList<Double>();
            ArrayList<String> vetorIntegrantes = new ArrayList<String>();
            PreparedStatement stmt = CON.con.prepareStatement("Select nome from integrantes");
            ResultSet rs = stmt.executeQuery();
            while (rs.next()){
                vetorIntegrantes.add(rs.getString("nome"));
            }
            while (vetorIntegrantes.size() < 6){
                vetorIntegrantes.add("Vazio");
            }
            //Mostrando o nome dos integrantes nos Labels e calculando valores
            Resumo telaResumo = new Resumo();
            if (!vetorIntegrantes.get(0).equals("Vazio")){
                telaResumo.setNomeIntegrante1(vetorIntegrantes.get(0));
                valorIndividual = Conta.calcularValorIndividual("1");
                telaResumo.setValorIntegrante1(valorIndividual);
                valoresIndividuais.add(valorIndividual);
            }
            if (!vetorIntegrantes.get(1).equals("Vazio")){
                telaResumo.setNomeIntegrante2(vetorIntegrantes.get(1));
                valorIndividual = Conta.calcularValorIndividual("2");
                telaResumo.setValorIntegrante2(valorIndividual);
                valoresIndividuais.add(valorIndividual);
            }
            if (!vetorIntegrantes.get(2).equals("Vazio")){
                telaResumo.setNomeIntegrante3(vetorIntegrantes.get(2));
                valorIndividual = Conta.calcularValorIndividual("3");
                telaResumo.setValorIntegrante3(valorIndividual);
                valoresIndividuais.add(valorIndividual);
            }
            if (!vetorIntegrantes.get(3).equals("Vazio")){
                telaResumo.setNomeIntegrante4(vetorIntegrantes.get(3));
                valorIndividual = Conta.calcularValorIndividual("4");
                telaResumo.setValorIntegrante4(valorIndividual);
                valoresIndividuais.add(valorIndividual);                
            }
            if (!vetorIntegrantes.get(4).equals("Vazio")){
                telaResumo.setNomeIntegrante5(vetorIntegrantes.get(4));
                valorIndividual = Conta.calcularValorIndividual("5");
                telaResumo.setValorIntegrante5(valorIndividual);
                valoresIndividuais.add(valorIndividual);
            }
            if (!vetorIntegrantes.get(5).equals("Vazio")){
                telaResumo.setNomeIntegrante6(vetorIntegrantes.get(5));
                valorIndividual = Conta.calcularValorIndividual("6");
                telaResumo.setValorIntegrante6(valorIndividual);
                valoresIndividuais.add(valorIndividual);
            }
            double valorTotal = 0;
            for (int i = 0; i < valoresIndividuais.size(); i++){
                valorTotal += valoresIndividuais.get(i);
            }
            telaResumo.setValorTotal(valorTotal);
            telaResumo.setVisible(true);
        } catch (SQLException e) {
            System.out.println(e);
            System.out.println("Deu erro!");
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_ResumoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cardapio().setVisible(true);
                Conta.abrirConta();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Resumo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
