/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tablet;

/**
 *
 * @author aluno
 */
public class Sobremesas extends javax.swing.JFrame {

    /**
     * Creates new form Pratos
     */
    public Sobremesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sobremesa4 = new javax.swing.JLabel();
        sobremesa3 = new javax.swing.JLabel();
        sobremesa1 = new javax.swing.JLabel();
        sobremesa2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ESCOLHA SUA SOBREMESA");
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(null);

        sobremesa4.setBackground(new java.awt.Color(255, 0, 0));
        sobremesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/sorvete.jpg"))); // NOI18N
        sobremesa4.setToolTipText("SORVETES DE DIVERSOS SABORES E COM COBERTURA.");
        sobremesa4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        sobremesa4.setOpaque(true);
        getContentPane().add(sobremesa4);
        sobremesa4.setBounds(540, 390, 325, 257);

        sobremesa3.setBackground(new java.awt.Color(0, 204, 255));
        sobremesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/mousse-maracuja-400x400.jpg"))); // NOI18N
        sobremesa3.setToolTipText("MOUSSES DE DIVERSOS SABORES.");
        sobremesa3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        sobremesa3.setOpaque(true);
        getContentPane().add(sobremesa3);
        sobremesa3.setBounds(150, 390, 325, 257);

        sobremesa1.setBackground(new java.awt.Color(0, 204, 255));
        sobremesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/PUDIM.jpg"))); // NOI18N
        sobremesa1.setToolTipText("PUDIM.");
        sobremesa1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        sobremesa1.setOpaque(true);
        getContentPane().add(sobremesa1);
        sobremesa1.setBounds(150, 110, 325, 257);

        sobremesa2.setBackground(new java.awt.Color(255, 0, 0));
        sobremesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Petit-Gateau-400x400.jpg"))); // NOI18N
        sobremesa2.setToolTipText("PETIT-GATEAU");
        sobremesa2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        sobremesa2.setOpaque(true);
        getContentPane().add(sobremesa2);
        sobremesa2.setBounds(540, 110, 325, 257);

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESCOLHA SUA SOBREMESA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 40, 410, 40);

        jButton1.setBackground(new java.awt.Color(255, 102, 51));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 220, 60, 270);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sobremesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sobremesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sobremesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sobremesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobremesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel sobremesa1;
    private javax.swing.JLabel sobremesa2;
    private javax.swing.JLabel sobremesa3;
    private javax.swing.JLabel sobremesa4;
    // End of variables declaration//GEN-END:variables
}
